# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim = {
    pname = "nvim";
    version = "e86c218fa3c816875e07e66d409070e8298959cc";
    src = fetchFromGitHub {
      owner = "unlsycn";
      repo = ".vim";
      rev = "e86c218fa3c816875e07e66d409070e8298959cc";
      fetchSubmodules = false;
      sha256 = "sha256-EflMLlRl574CvG+mRBR5GoGFSyGEHc67uplz7cyZNgY=";
    };
    date = "2025-04-01";
  };
  nvim-vscode = {
    pname = "nvim-vscode";
    version = "dd9ddb77c028b0212839bd98fd2f4a406eeb4bb1";
    src = fetchFromGitHub {
      owner = "unlsycn";
      repo = ".vim";
      rev = "dd9ddb77c028b0212839bd98fd2f4a406eeb4bb1";
      fetchSubmodules = false;
      sha256 = "sha256-sdvD8RZi9qwnHz0Cuv9WYjyQxmMKmfhS4Y0KzKFaB9g=";
    };
    date = "2024-12-30";
  };
}
