# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim = {
    pname = "nvim";
    version = "6e94d85324363f2c461a2a6c7283908b9a72d557";
    src = fetchFromGitHub {
      owner = "unlsycn";
      repo = ".vim";
      rev = "6e94d85324363f2c461a2a6c7283908b9a72d557";
      fetchSubmodules = false;
      sha256 = "sha256-m4DtduON5g9iw5yEi/1frbs0CVYmRvra6uOeY5nulkw=";
    };
    date = "2025-10-09";
  };
  nvim-vscode = {
    pname = "nvim-vscode";
    version = "78da4ac7deefe0979b65bcb5549eda475db21abe";
    src = fetchFromGitHub {
      owner = "unlsycn";
      repo = ".vim";
      rev = "78da4ac7deefe0979b65bcb5549eda475db21abe";
      fetchSubmodules = false;
      sha256 = "sha256-Ex2NameFgpWkDsFSw9qZMYJko3xocWvJM6Gb/rp1X88=";
    };
    date = "2025-10-09";
  };
}
