# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim = {
    pname = "nvim";
    version = "0534c4742d356efb24a5133e34fdc5fc3a36c600";
    src = fetchFromGitHub {
      owner = "unlsycn";
      repo = ".vim";
      rev = "0534c4742d356efb24a5133e34fdc5fc3a36c600";
      fetchSubmodules = false;
      sha256 = "sha256-Vt4wXpqRoh4qEl/x9xOJL0DImPfU0vQBoeIQfc6KLpM=";
    };
    date = "2024-09-21";
  };
  nvim-vscode = {
    pname = "nvim-vscode";
    version = "dd9ddb77c028b0212839bd98fd2f4a406eeb4bb1";
    src = fetchFromGitHub {
      owner = "unlsycn";
      repo = ".vim";
      rev = "dd9ddb77c028b0212839bd98fd2f4a406eeb4bb1";
      fetchSubmodules = false;
      sha256 = "sha256-sdvD8RZi9qwnHz0Cuv9WYjyQxmMKmfhS4Y0KzKFaB9g=";
    };
    date = "2024-12-30";
  };
}
