# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ];
      postDeviceCommands = lib.mkBefore (builtins.readFile ./restore-home.sh);
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "defaults"
      "size=25%"
      "mode=755"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/82eec0cb-2c5e-4af1-8e6c-f0218b0d28f3";
    # There was a race condition between mounting stateless /home and bind mounting the persistent directories
    neededForBoot = true;
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
    ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/82eec0cb-2c5e-4af1-8e6c-f0218b0d28f3";
    neededForBoot = true;
    fsType = "btrfs";
    options = [
      "subvol=@persist"
      "compress=zstd"
    ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/82eec0cb-2c5e-4af1-8e6c-f0218b0d28f3";
    fsType = "btrfs";
    options = [
      "subvol=@var"
      "compress=zstd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/82eec0cb-2c5e-4af1-8e6c-f0218b0d28f3";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress=zstd"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/f707f48f-ce6a-4303-9373-54db6b361903";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/F4D3-2BFB";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/30b808f1-77a5-46d2-b5fa-205aff0b2ecd"; }
  ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
